spring:
  config:
    activate:
      on-profile: prod

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true