spring:
  config:
    activate:
      on-profile: prod

  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}